version: "3.7"
services:
  node-api:
    build: .
    command: nodemon --exec babel-node src/server/start.js
    volumes:
      - /chord-app:/chord-app
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
