version: "3.7"
services:
  node-api:
    build: .
    ports:
      - target: 8080
        published: 2020
        protocol: tcp
        mode: host
  react-client:
    build: ./src/client/
    ports:
      - target: 3000
        published: 3030
        protocol: tcp
        mode: host