name: testing actions

on:
  push:
    branches:
      - actions-sandbox

jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Lets go!"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

