name: testing actions

on:
  push:
    branches: [actions-sandbox]
    paths:
      - 'src/server/**'


jobs:
  run-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Lets go!"
      - name: running a multi line command syntax
        run: |
          node -v
          npm -v

